### ISSUE TITLE
"The API did not respond or did not accept your request."

### ISSUE THREAD

**Issue by cg089** [tmjo/ha-norwegianweather#1] opened 2021-12-02 13:41 UTC
Hi,
thanks for your plugin, always great to see people relay on the awesome met.no data!

In Home Assistant 2021.11.2 and 2021.11.5 I unfortunately get the error "The API did not respond or did not accept your request.".

Steps to reproduce:
1. Install plugin (tried both manual and with hacs)
2. Add new integration
3. input data in plugin

Do I need an own api key and insert it anywhere?

**Comment by tmjo** [comment] 2021-12-03 16:21
Hi @cg089 and thanks for your input.

I am on 2021.11.4 and it seems to be working fine. I also tried to add a new location to my system (several locations are possible) and the new one was also accepted without problems.

Could it be that you used some invalid input in the config settings? 

I was able to reproduce the same error when I had something wrong in the longitude/latitude, could that be the case? I'll try to figure out why (and perhaps improve the error message), but it would be helpful if you could test again with this in mind. I tried Stavanger (58.960018998741155, 5.731992810334487) as an example, would you mind testing the same and see if it works?

**Comment by tmjo** [comment] 2021-12-03 16:25
You could also test your own location directly on the API to verify if it works (open the GET complete "folder", insert lon/lat and click the "Try it out"-button):

https://api.met.no/weatherapi/locationforecast/2.0/documentation#!/data/get_complete_format

**Comment by cg089** [comment] 2021-12-03 17:25
Thats interesting!

It works with your location data. However, mine (Munich) throws an api error.
I tried 48.14073375677628, 11.560368580977606 which is Munich central station.

However, the met api works normally pretty good for Munich. The "try it out" button sends perfect data on that location!

**Comment by tmjo** [comment] 2021-12-03 22:06
You're right, I was able to reproduce it just like you described. It should be fixed now in the latest release.

Seems like not all detailed data is available on all locations, so there was some dirty code without proper error handling that made something crash. Hope it is good now!

Thanks for your feedback.

**Comment by cg089** [comment] 2021-12-03 22:39
Awesome, thanks for the quick fix!

**Closed as completed** 2021-12-03 23:29 UTC
